# TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'sainnhe/tmux-fzf'

# Misc settings
set -g extended-keys on
set -g extended-keys-format csi-u

set -g default-terminal 'tmux-256color'
set -g allow-passthrough on
set -sg escape-time 0
set -g focus-events on
set -g xterm-keys on

if-shell '[ -z "$DEVPOD" ]' {
  # outer tmux
  set -as terminal-features ',xterm-ghostty:RGB'
  set -as terminal-features ',xterm-256color:RGB'

  set -g set-clipboard on
} {
  # inner tmux
  # rebind prefix
  set -g prefix C-a
  unbind C-b
  bind C-a send-prefix

  set -as terminal-features ',tmux-256color:RGB'
  # This is specific to devpod, see https://github.com/loft-sh/devpod/issues/932
  set -ag terminal-overrides ',*:cud1=\E[1B'

  set -g set-clipboard external
}

bind r send-keys C-l \; refresh-client -S

# Initialize TPM (keep this at bottom)
run '~/.tmux/plugins/tpm/tpm'
