# TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'laktak/extrakto'

# Misc settings
set -g extended-keys on
set -g extended-keys-format csi-u

# rebind prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Initialize TPM (keep this at bottom)
run '~/.tmux/plugins/tpm/tpm'
