vault:
  profiles:
    dev:
      env_prefix: "secret/data/dev/env"
      files_prefix: "secret/data/dev/files"

defaults:
  profile: dev

env:
  commands:
    - name: pi
      variables:
        - name: GEMINI_API_KEY
        - name: PERPLEXITY_API_KEY
        - name: OPENROUTER_API_KEY
    - name: gh
      variables:
        - name: GH_TOKEN
    - name: ngrok
      variables:
        - name: NGROK_AUTHTOKEN
files:
  - path: ~/.pi/agent/auth.json
    key: pi_agent_auth
  - path: ~/.pi/agent/models.json
    key: pi_agent_models
